import "./css/style.css";

import { Inter } from "next/font/google";
import Head from "next/head";

import Header from "@/components/ui/header";
import Banner from "@/components/banner";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://www.carbonblocks.co/" />
        <meta property="og:title" content="CarbonBlocks" />
        <meta property="og:description" content="Building the carbon economy" />
        <meta
          property="og:image"
          content="../../public/images/carbonBlocks2k.svg"
        />
        <meta
          name="thumbnail"
          content="../../public/images/carbonBlocks2k.svg"
        />
        <link rel="shortcut icon" href="/images/carbneg_logo800.png" />

        {/* <link rel="shortcut icon" href="../../public/images/favicon.ico" /> */}
        {/* <link rel="icon" href="../favicon.ico" type="image/x-icon" /> */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
      </head>
      <body
        className={`${inter.variable} font-inter antialiased bg-white text-gray-900 tracking-tight`}
      >
        <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
          <Header />
          {children}
          {/* <Banner /> */}
        </div>
      </body>
    </html>
  );
}
